-- Disable RLS for all tables (development environment)
ALTER TABLE public.media DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.asps DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_media_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.budgets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.actuals DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_budgets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_actuals DISABLE ROW LEVEL SECURITY;
